[2024-07-05T08:24:16.899+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T08:24:16.924+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.get_failed_dag manual__2024-07-05T08:18:45.478464+00:00 [queued]>
[2024-07-05T08:24:16.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Fail_Dags_Monitor.get_failed_dag manual__2024-07-05T08:18:45.478464+00:00 [queued]>
[2024-07-05T08:24:16.930+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-07-05T08:24:16.938+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_failed_dag> on 2024-07-05 08:18:45.478464+00:00
[2024-07-05T08:24:16.946+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Fail_Dags_Monitor', 'get_failed_dag', 'manual__2024-07-05T08:18:45.478464+00:00', '--job-id', '503', '--raw', '--subdir', 'DAGS_FOLDER/fail_dags_monitor.py', '--cfg-path', '/tmp/tmpukvze581']
[2024-07-05T08:24:16.948+0000] {standard_task_runner.py:91} INFO - Job 503: Subtask get_failed_dag
[2024-07-05T08:24:16.951+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=47547) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-05T08:24:16.951+0000] {standard_task_runner.py:63} INFO - Started process 47549 to run task
[2024-07-05T08:24:16.982+0000] {task_command.py:426} INFO - Running <TaskInstance: Fail_Dags_Monitor.get_failed_dag manual__2024-07-05T08:18:45.478464+00:00 [running]> on host 0b64c9d791b9
[2024-07-05T08:24:17.052+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='congminh.nguyen@onpoint.vn' AIRFLOW_CTX_DAG_ID='Fail_Dags_Monitor' AIRFLOW_CTX_TASK_ID='get_failed_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-07-05T08:18:45.478464+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-05T08:18:45.478464+00:00'
[2024-07-05T08:24:17.053+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-05T08:24:17.431+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/***/dags
[2024-07-05T08:24:17.458+0000] {python.py:237} INFO - Done. Returned value was: [{'id': 187, 'run_id': 'scheduled__2024-07-03T09:56:00+00:00', 'state': 'failed', 'dag_id': 'Email_test_dag', 'run_type': 'scheduled', 'execution_date': '2024-07-03T09:56:00+00:00', 'start_date': '2024-07-04T09:56:00.202702+00:00', 'end_date': '2024-07-04T09:56:25.480316+00:00'}, {'id': 167, 'run_id': 'manual__2024-07-04T03:32:53.290166+00:00', 'state': 'failed', 'dag_id': 'Email_test_dag', 'run_type': 'manual', 'execution_date': '2024-07-04T03:32:53.290166+00:00', 'start_date': '2024-07-04T04:09:37.884658+00:00', 'end_date': '2024-07-04T04:10:06.721963+00:00'}]
[2024-07-05T08:24:17.459+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-05T08:24:17.471+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Fail_Dags_Monitor, task_id=get_failed_dag, run_id=manual__2024-07-05T08:18:45.478464+00:00, execution_date=20240705T081845, start_date=20240705T082416, end_date=20240705T082417
[2024-07-05T08:24:17.512+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-05T08:24:17.532+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-05T08:24:17.533+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
